name: electrical_junctions_domain

environment:
  sdk: ">=3.10.0-0 <4.0.0"

dependencies:
  melos: ^7.4.0

workspace:
  - packages/domain_entities
  - packages/domain_usecases
  - packages/domain_contracts

  # Pulled from flutterfire, to learn how to use melos for monorepo management. See
melos:
  name: electrical_junctions_domain
  repository: https://github.com/staylorx/electrical_junctions_domain

  packages:
    - packages/**
    - tests

  command:
    bootstrap:
      runPubGetInParallel: true
      # usePubspecOverrides: true
